name: develop-release

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        path: src/github.com/containerd/accelerated-container-image
        fetch-depth: 100

    - name: install Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.18.2'

    - name: set env
      shell: bash
      run: |
        echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
        echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
        echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
        sudo apt update
        sudo apt install -y nfpm

    - name: build
      working-directory: src/github.com/containerd/accelerated-container-image
      run: |
        make
        nfpm pkg --packager deb --target /tmp/
        nfpm pkg --packager rpm --target /tmp/

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Development Build"
        files: |
          /tmp/overlaybd-snapshotter*.deb
          /tmp/overlaybd-snapshotter*.rpm
